new

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,29 +1,25 @@
-name: Deploy to Github Pages
-on:
-    push:
-        branches:
-            - development
+#!/usr/bin/env sh
 
-jobs:
-    deploy:
-        name: Deploy Application
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout Repo
-              uses: actions/checkout@main
-            - name: Create Node Environment
-              uses: actions/setup-node@v1
-              with: 
-                node-version: 16.x
-            - name: Install Packages and Build Application
-              run: |
-                npm install -g @vue/cli yarn
-                yarn install
-                yarn build
-            - name: Deploy
-              uses: s0/git-publish-subdir-action@develop
-              env:
-                REPO: self
-                BRANCH: main
-                FOLDER: dist
-                GITHUB_TOKEN: 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
+# abort on errors
+set -e
+
+# build
+npm run build
+
+# navigate into the build output directory
+cd dist
+
+# if you are deploying to a custom domain
+# echo 'www.example.com' > CNAME
+
+git init
+git add -A
+git commit -m 'deploy'
+
+# if you are deploying to https://<USERNAME>.github.io
+# git push -f git@github.com:<USERNAME>/<USERNAME>.github.io.git main
+
+# if you are deploying to https://<USERNAME>.github.io/<REPO>
+git push -f git@github.com:MichaelOtilla/CV.git main:gh-pages
+
+cd -
